[globals]
years = [2024, 2025]
years_short = [24, 25]
symbols = ["", ".", "*", "**", "!"]
months = ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12"]
numbers = ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"]

# Example2025
# Example*2025
[[pattern]]
importance = 10
code = """
if not complex_password:
    passwords += [
        f"{first_name[0].upper()}{first_name[1:].lower()}{symbol}{year}"
        for year in years
        for symbol in symbols
    ]
"""

# example2025
# example*2025
[[pattern]]
importance = 10
code = """
if not complex_password:
    passwords += [
        f"{first_name.lower()}{symbol}{year}"
        for year in years
        for symbol in symbols
    ]
"""

# EXAMPLE2025
# EXAMPLE*2025
[[pattern]]
importance = 10
code = """
if not complex_password:
    passwords += [
        f"{first_name.upper()}{symbol}{year}"
        for year in years
        for symbol in symbols
    ]
"""

# Example2025
# Example*2025
[[pattern]]
importance = 10
code = """
if not complex_password:
    passwords += [
        f"{first_name[0].upper()}{first_name[1:].lower()}{symbol}{month}{year}"
        for year in years
        for symbol in symbols
        for month in months
    ]
"""

# example2025
# example*2025
[[pattern]]
importance = 10
code = """
if not complex_password:
    passwords += [
        f"{first_name.lower()}{symbol}{month}{year}"
        for year in years
        for symbol in symbols
        for month in months
    ]
"""

# EXAMPLE2025
# EXAMPLE*2025
[[pattern]]
importance = 10
code = """
if not complex_password:
    passwords += [
        f"{first_name.upper()}{symbol}{month}{year}"
        for year in years
        for symbol in symbols
        for month in months
    ]
"""


# Ee2025
# Ee*2025
[[pattern]]
importance = 10
code = """
passwords += [
    f"{first_name[0].upper()}{last_name[0].lower()}{symbol}{year}"
    for symbol in symbols
    for year in years
]
"""

# Ee062025
# Ee*062025
[[pattern]]
importance = 10
code = """
passwords += [
    f"{first_name[0].upper()}{last_name[0].lower()}{symbol}{month}{year}"
    for symbol in symbols
    for year in years
    for month in months
]
"""

# EE2025
# EE*2025
[[pattern]]
importance = 10
code = """
passwords += [
    f"{first_name[0].upper()}{last_name[0].upper()}{symbol}{year}"
    for symbol in symbols
    for year in years
]
"""

# EE062025
# EE*062025
[[pattern]]
importance = 10
code = """
passwords += [
    f"{first_name[0].upper()}{last_name[0].upper()}{symbol}{month}{year}"
    for symbol in symbols
    for year in years
    for month in months
]
"""

# ee2025
# ee*2025
[[pattern]]
importance = 10
code = """
passwords += [
    f"{first_name[0].lower()}{last_name[0].lower()}{symbol}{year}"
    for symbol in symbols
    for year in years
]
"""

# ee062025
# ee*062025
[[pattern]]
importance = 10
code = """
passwords += [
    f"{first_name[0].lower()}{last_name[0].lower()}{symbol}{month}{year}"
    for symbol in symbols
    for year in years
    for month in months
]
"""

# eE2025
# eE*2025
[[pattern]]
importance = 10
code = """
passwords += [
    f"{first_name[0].lower()}{last_name[0].upper()}{symbol}{year}"
    for symbol in symbols
    for year in years
]
"""

# eE062025
# eE*062025
[[pattern]]
importance = 10
code = """
passwords += [
    f"{first_name[0].lower()}{last_name[0].upper()}{symbol}{month}{year}"
    for symbol in symbols
    for year in years
    for month in months
]
"""

# Ee25
# Ee*25
[[pattern]]
importance = 10
code = """
passwords += [
    f"{first_name[0].upper()}{last_name[0].lower()}{symbol}{year}"
    for symbol in symbols
    for year in years_short
]
"""

# Ee0625
# Ee*0625
[[pattern]]
importance = 10
code = """
passwords += [
    f"{first_name[0].upper()}{last_name[0].lower()}{symbol}{month}{year}"
    for symbol in symbols
    for year in years_short
    for month in months
]
"""

# eE25
# eE*25
[[pattern]]
importance = 10
code = """
passwords += [
    f"{first_name[0].lower()}{last_name[0].upper()}{symbol}{year}"
    for symbol in symbols
    for year in years_short
]
"""

# eE0625
# eE*0625
[[pattern]]
importance = 10
code = """
passwords += [
    f"{first_name[0].lower()}{last_name[0].upper()}{symbol}{month}{year}"
    for symbol in symbols
    for year in years_short
    for month in months
]
"""

# E123456789E
[[pattern]]
importance = 10
code = """
digits = [str(i) for i in range(1, 10)]  # ['1', '2', ..., '9']
first_initial = first_name[0]
last_initial = last_name[0]

variants = []
for i in range(1, len(digits) + 1):
    number = ''.join(digits[:i])  # '1', '12', '123', ..., '123456789'
    reversed_digits = number[::-1]
    variants.extend([
        f"{first_initial.upper()}{number}{last_initial.upper()}",
        f"{first_initial.lower()}{number}{last_initial.upper()}",
        f"{first_initial.upper()}{number}{last_initial.lower()}",
        f"{first_initial.lower()}{number}{last_initial.lower()}",
        f"{first_initial.upper()}{reversed_digits}{last_initial.upper()}",
        f"{first_initial.lower()}{reversed_digits}{last_initial.upper()}",
        f"{first_initial.upper()}{reversed_digits}{last_initial.lower()}",
        f"{first_initial.lower()}{reversed_digits}{last_initial.lower()}",
    ])

passwords += variants
"""

# Semi static Turkish
[[pattern]]
importance = 9
code = """
passwords += [
    f"Bugun{symbol}{year}"
    for symbol in symbols
    for year in years
    for month in months
]
passwords += [
    f"Bugun{symbol}{month}{year}"
    for symbol in symbols
    for year in years
    for month in months
]
passwords += [
    f"Dun{symbol}{year}"
    for symbol in symbols
    for year in years
    for month in months
]
passwords += [
    f"Dun{symbol}{month}{year}"
    for symbol in symbols
    for year in years
    for month in months
]
passwords += [
    f"Yarin{symbol}{year}"
    for symbol in symbols
    for year in years
    for month in months
]
passwords += [
    f"Yarin{symbol}{month}{year}"
    for symbol in symbols
    for year in years
    for month in months
]
"""


[[pattern]]
importance = 10000
code = """
passwords.append("Aa12456")
"""

# Plakalar Turkish
[[pattern]]
importance = 1
code = """
passwords.append("Aa12456")
"""