[globals]
years = [2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025]
years_short = [18, 19, 20, 21, 22, 23, 24, 25]
symbols = ["", ".", "*", "**", "!"]
symbols2 = ["!!**", "!*"]
months = ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12"]
numbers = ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"]

# Example2025
# Example*2025
# Example25
# Example*25
[[pattern]]
importance = 10
code = """
passwords += [
    f"{first_name[0].upper()}{first_name[1:].lower()}{symbol}{year}"
    for year in years
    for symbol in symbols
]
passwords += [
    f"{first_name[0].upper()}{first_name[1:].lower()}{symbol}{year}"
    for year in years_short
    for symbol in symbols
]
"""

# example2025
# example*2025
# example25
# example*25
[[pattern]]
importance = 10
code = """
passwords += [
    f"{first_name.lower()}{symbol}{year}"
    for year in years
    for symbol in symbols
]
passwords += [
    f"{first_name.lower()}{symbol}{year}"
    for year in years_short
    for symbol in symbols
]
"""

# EXAMPLE2025
# EXAMPLE*2025
# EXAMPLE25
# EXAMPLE*25
[[pattern]]
importance = 10
code = """
passwords += [
    f"{first_name.upper()}{symbol}{year}"
    for year in years
    for symbol in symbols
]
passwords += [
    f"{first_name.upper()}{symbol}{year}"
    for year in years_short
    for symbol in symbols
]
"""

# Example062025
# Example*062025
# Example0625
# Example*0625
[[pattern]]
importance = 10
code = """
passwords += [
    f"{first_name[0].upper()}{first_name[1:].lower()}{symbol}{month}{year}"
    for year in years
    for symbol in symbols
    for month in months
]
passwords += [
    f"{first_name[0].upper()}{first_name[1:].lower()}{symbol}{month}{year}"
    for year in years_short
    for symbol in symbols
    for month in months
]
"""

# example062025
# example*062025
[[pattern]]
importance = 10
code = """
passwords += [
    f"{first_name.lower()}{symbol}{month}{year}"
    for year in years
    for symbol in symbols
    for month in months
]
"""

# EXAMPLE062025
# EXAMPLE*062025
[[pattern]]
importance = 10
code = """
passwords += [
    f"{first_name.upper()}{symbol}{month}{year}"
    for year in years
    for symbol in symbols
    for month in months
]
"""



# Ee2025
# Ee*2025
[[pattern]]
importance = 10
code = """
passwords += [
    f"{first_name[0].upper()}{last_name[0].lower()}{symbol}{year}"
    for symbol in symbols
    for year in years
]
"""

# Ee062025
# Ee*062025
[[pattern]]
importance = 10
code = """
passwords += [
    f"{first_name[0].upper()}{last_name[0].lower()}{symbol}{month}{year}"
    for symbol in symbols
    for year in years
    for month in months
]
"""

# ee062025 (last_name first)
# ee06*2025 (last_name first)
[[pattern]]
importance = 10
code = """
passwords += [
    f"{last_name[0].lower()}{first_name[0].lower()}{month}{symbol}{year}"
    for symbol in symbols
    for year in years
    for month in months
]
"""

# EE2025
# EE*2025
[[pattern]]
importance = 10
code = """
passwords += [
    f"{first_name[0].upper()}{last_name[0].upper()}{symbol}{year}"
    for symbol in symbols
    for year in years
]
"""

# EE062025
# EE*062025
[[pattern]]
importance = 10
code = """
passwords += [
    f"{first_name[0].upper()}{last_name[0].upper()}{symbol}{month}{year}"
    for symbol in symbols
    for year in years
    for month in months
]
"""

# ee2025
# ee*2025
[[pattern]]
importance = 10
code = """
passwords += [
    f"{first_name[0].lower()}{last_name[0].lower()}{symbol}{year}"
    for symbol in symbols
    for year in years
]
"""

# ee062025
# ee*062025
[[pattern]]
importance = 10
code = """
passwords += [
    f"{first_name[0].lower()}{last_name[0].lower()}{symbol}{month}{year}"
    for symbol in symbols
    for year in years
    for month in months
]
"""

# eE2025
# eE*2025
[[pattern]]
importance = 10
code = """
passwords += [
    f"{first_name[0].lower()}{last_name[0].upper()}{symbol}{year}"
    for symbol in symbols
    for year in years
]
"""

# eE062025
# eE*062025
[[pattern]]
importance = 10
code = """
passwords += [
    f"{first_name[0].lower()}{last_name[0].upper()}{symbol}{month}{year}"
    for symbol in symbols
    for year in years
    for month in months
]
"""

# Ee25
# Ee*25
[[pattern]]
importance = 10
code = """
passwords += [
    f"{first_name[0].upper()}{last_name[0].lower()}{symbol}{year}"
    for symbol in symbols
    for year in years_short
]
"""

# Ee0625
# Ee*0625
[[pattern]]
importance = 10
code = """
passwords += [
    f"{first_name[0].upper()}{last_name[0].lower()}{symbol}{month}{year}"
    for symbol in symbols
    for year in years_short
    for month in months
]
"""

# eE25
# eE*25
[[pattern]]
importance = 10
code = """
passwords += [
    f"{first_name[0].lower()}{last_name[0].upper()}{symbol}{year}"
    for symbol in symbols
    for year in years_short
]
"""

# eE0625
# eE*0625
[[pattern]]
importance = 10
code = """
passwords += [
    f"{first_name[0].lower()}{last_name[0].upper()}{symbol}{month}{year}"
    for symbol in symbols
    for year in years_short
    for month in months
]
"""

# E123456789E
[[pattern]]
importance = 10
code = """
digits = [str(i) for i in range(1, 10)]
digits2 = [str(i) for i in range(9, 0, -1)]
first_initial = first_name[0]
last_initial = last_name[0]

variants = []
for i in range(1, len(digits) + 1):
    number = ''.join(digits[:i])  # '1', '12', '123', ..., '123456789'
    variants.extend([
        f"{first_initial.upper()}{number}{last_initial.upper()}",
        f"{first_initial.lower()}{number}{last_initial.upper()}",
        f"{first_initial.upper()}{number}{last_initial.lower()}",
        f"{first_initial.lower()}{number}{last_initial.lower()}",
    ])

for i in range(1, len(digits2) + 1):
    number = ''.join(digits2[:i])  # '1', '12', '123', ..., '123456789'
    variants.extend([
        f"{first_initial.upper()}{number}{last_initial.upper()}",
        f"{first_initial.lower()}{number}{last_initial.upper()}",
        f"{first_initial.upper()}{number}{last_initial.lower()}",
        f"{first_initial.lower()}{number}{last_initial.lower()}",
    ])

passwords += variants
"""

# EXAMPLE.E2025
[[pattern]]
importance = 8
code = """
passwords += [
    f"{first_name.upper()}.{last_name[0].upper()}{year}"
    for year in years
]
"""

# 2025Example
[[pattern]]
importance = 8
code = """
passwords += [
    f"{year}{first_name[0].upper()}{first_name[1:].lower()}"
    for year in years
]
"""

# eexample25
# Eexample25
[[pattern]]
importance = 8
code = """
passwords += [
    f"{first_name[0].lower()}{last_name.lower()}{year}"
    for year in years_short
]
passwords += [
    f"{first_name[0].upper()}{last_name.lower()}{year}"
    for year in years_short
]
"""

# Slices of first_name and last_name
# First name up to 4, last name up to 4
[[pattern]]
importance = 7
code = """
max_len = 4
max1 = min(len(first_name), max_len)
max2 = min(len(last_name), max_len)

slices = [
    word1[:i] + word2[:j]
    for i in range(0, max1 + 1)
    for j in range(0, max2 + 1)
    if i != 0 or j != 0
]

passwords += [
    f"{slice}{year}"
    for slice in slices
    for year in years
]
passwords += [
    f"{slice}{year}"
    for slice in slices
    for year in years_short
]
passwords += [
    f"{slice}{month}{year}"
    for slice in slices
    for month in months
    for year in years
]
passwords += [
    f"{slice}{month}{year}"
    for slice in slices
    for month in months
    for year in years_short
]
passwords += [
    f"{slice[0].upper()}{slice[1:].lower()}{year}"
    for slice in slices
    for year in years
]
passwords += [
    f"{slice[0].upper()}{slice[1:].lower()}{year}"
    for slice in slices
    for year in years_short
]
passwords += [
    f"{slice[0].upper()}{slice[1:].lower()}{month}{year}"
    for slice in slices
    for month in months
    for year in years
]
passwords += [
    f"{slice[0].upper()}{slice[1:].lower()}{month}{year}"
    for slice in slices
    for month in months
    for year in years_short
]
"""


# exam2025
[[pattern]]
importance = 8
code = """
if len(first_name) >= 4:
    passwords += [
        f"{first_name[0:4].lower()}{year}"
        for year in years
    ]
"""

# exae2025
# exae25
[[pattern]]
importance = 8
code = """
if len(first_name) >= 3:
    passwords += [
        f"{first_name[0:3].lower()}{last_name[0].lower()}{year}"
        for year in years
    ]
    passwords += [
        f"{first_name[0:3].lower()}{last_name[0].lower()}{year}"
        for year in years_short
    ]
"""

# exe2025
# exe25
# Exe2025
# Exe25
[[pattern]]
importance = 8
code = """
if len(first_name) >= 2:
    passwords += [
        f"{first_name[0:2].lower()}{last_name[0].lower()}{year}"
        for year in years
    ]
    passwords += [
        f"{first_name[0:2].lower()}{last_name[0].lower()}{year}"
        for year in years_short
    ]
    passwords += [
        f"{first_name[0].upper()}{first_name[1].lower()}{last_name[0].lower()}{year}"
        for year in years
    ]
    passwords += [
        f"{first_name[0].upper()}{first_name[1].lower()}{last_name[0].lower()}{year}"
        for year in years_short
    ]
"""

# eexa2025
# eexa25
# Eexa2025
# Eexa25
[[pattern]]
importance = 8
code = """
if len(last_name) >= 3:
    passwords += [
        f"{first_name[0].lower()}{last_name[0:3].lower()}{year}"
        for year in years
    ]
    passwords += [
        f"{first_name[0].lower()}{last_name[0:3].lower()}{year}"
        for year in years_short
    ]
    passwords += [
        f"{first_name[0].upper()}{last_name[0:3].lower()}{year}"
        for year in years
    ]
    passwords += [
        f"{first_name[0].upper()}{last_name[0:3].lower()}{year}"
        for year in years_short
    ]
"""

# exex2025
# exex25
# Exex2025
# Exex25
[[pattern]]
importance = 8
code = """
if len(first_name) >= 2 and len(last_name) >= 2:
    passwords += [
        f"{first_name[0:1].lower()}{last_name[0:1].lower()}{year}"
        for year in years
    ]
    passwords += [
        f"{first_name[0:1].lower()}{last_name[0:1].lower()}{year}"
        for year in years_short
    ]
    passwords += [
        f"{first_name[0].upper()}{first_name[1].lower()}{last_name[0:1].lower()}{year}"
        for year in years
    ]
    passwords += [
        f"{first_name[0].upper()}{first_name[1].lower()}{last_name[0:1].lower()}{year}"
        for year in years_short
    ]
"""

# (E)xample(E)xampl(E)0625
[[pattern]]
importance = 8
code = """
passwords += [
    f"{first_name[0].upper()}{last_name[0].upper()}{last_name[-1].upper()}{month}{year}"
    for month in months
    for year in years_short
]
"""

# 123456EE
[[pattern]]
importance = 8
code = """
passwords += [
    f"123456{first_name[0].upper()}{last_name[0].upper()}"
]
"""


#################
# Company Stuff #
#################

# Company2025
# Company2025*
[[pattern]]
importance = 9
code = """
passwords += [
    f"{company_name[0].upper()}{company_name[1:].lower()}{year}"
    for year in years
    for company_name in company_names
]
passwords += [
    f"{company_name[0].upper()}{company_name[1:].lower()}{year}{symbol}"
    for symbol in symbols
    for year in years
    for company_name in company_names
]
passwords += [
    f"{company_name[0].upper()}{company_name[1:].lower()}{year}{symbol}"
    for symbol in symbols2
    for year in years
    for company_name in company_names
]
"""

# cOmpany2025
# cOmpany2025*
[[pattern]]
importance = 9
code = """
passwords += [
    f"{company_name[0].lower()}{company_name[0].upper()}{company_name[2:].lower()}{year}"
    for year in years
    for company_name in company_names
]
passwords += [
    f"{company_name[0].lower()}{company_name[0].upper()}{company_name[2:].lower()}{year}{symbol}"
    for symbol in symbols
    for year in years
    for company_name in company_names
]
passwords += [
    f"{company_name[0].lower()}{company_name[0].upper()}{company_name[2:].lower()}{year}{symbol}"
    for symbol in symbols2
    for year in years
    for company_name in company_names
]
"""



# Semi static Turkish
[[pattern]]
importance = 2
code = """
passwords += [
    f"Bugun{symbol}{year}"
    for symbol in symbols
    for year in years
    for month in months
]
passwords += [
    f"Bugun{symbol}{month}{year}"
    for symbol in symbols
    for year in years
    for month in months
]
passwords += [
    f"Dun{symbol}{year}"
    for symbol in symbols
    for year in years
    for month in months
]
passwords += [
    f"Dun{symbol}{month}{year}"
    for symbol in symbols
    for year in years
    for month in months
]
passwords += [
    f"Yarin{symbol}{year}"
    for symbol in symbols
    for year in years
    for month in months
]
passwords += [
    f"Yarin{symbol}{month}{year}"
    for symbol in symbols
    for year in years
    for month in months
]
passwords += [
    f"Acilis{symbol}{year}"
    for symbol in symbols
    for year in years
]
"""

[[pattern]]
importance = 10000
code = """
passwords += ["Aa123456"]
"""