[pattern1]
template = "{first_name_first_char_capitalized}*{year}"
code = """
passwords += [
    f"{first_name[0].upper()}{symbol}{first_name[1:]}{year}"
    for year in years
    for symbol in symbols
]
"""
importance = 10
years = [2024, 2025]
symbols = ["", "*"]