[globals]
years = [2024, 2025]
symbols = ["", "*", "**"]
months = ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12"]

[[pattern]]
code = """
passwords += [
    f"{first_name[0].upper()}{first_name[1:]}{symbol}{year}"
    for year in years
    for symbol in symbols
]
"""
importance = 10
years = [2024, 2025]
symbols = ["", "*", "**"]

[[pattern]]
code = """
passwords += [
    f"{first_name[0].upper()}{last_name[0]}{symbol}{year}"
    for symbol in symbols
    for year in years
]
passwords += [
    f"{first_name[0].upper()}{last_name[0]}{symbol}{month}{year}"
    for symbol in symbols
    for year in years
    for month in months
]
passwords += [
    f"{first_name[0]}{last_name[0].upper()}{symbol}{year}"
    for symbol in symbols
    for year in years
]
passwords += [
    f"{first_name[0]}{last_name[0].upper()}{symbol}{month}{year}"
    for symbol in symbols
    for year in years
    for month in months
]
"""
importance = 10

[[pattern]]
code = """
passwords += [
    f"Bugun{symbol}{year}"
    for symbol in symbols
    for year in years
    for month in months
]
passwords += [
    f"Bugun{symbol}{month}{year}"
    for symbol in symbols
    for year in years
    for month in months
]
passwords += [
    f"Dun{symbol}{year}"
    for symbol in symbols
    for year in years
    for month in months
]
passwords += [
    f"Dun{symbol}{month}{year}"
    for symbol in symbols
    for year in years
    for month in months
]
passwords += [
    f"Yarin{symbol}{year}"
    for symbol in symbols
    for year in years
    for month in months
]
passwords += [
    f"Yarin{symbol}{month}{year}"
    for symbol in symbols
    for year in years
    for month in months
]
"""
importance = 9

[[pattern]]
importance = 1
code = """
passwords.append("Spring2024!")
passwords.append("Welcome123")
passwords.append("Qwerty!2023")
"""